### PR TITLE
Add buttercms plugin code

### PR DESCRIPTION
**Pull request by lauragift21**

### CODE REVIEW

**Comment by jakelumetta** [comment]
@courcelan mind taking a look at this and trying it out?

**Comment by courcelan** [comment]
This looks really nice for a start. It can be released as is but definitely needs documentation.

 It looks like you have to set up the plugin multiple times. This makes some sense for an initial release. 

As few things:

1. When declaring the plugin multiple times, the user has to input their API key multiple times. Additionally it needs to be hard-coded rather than through a `.env` file. I would make `authToken` "optional", so that the user can override it manually if desired, but by default it checks for a `.env` file.
```
static defaultOptions() {
    return {
      authToken: process.env.GRIDSOME_BUTTER_AUTHTOKEN || process.env.BUTTER_AUTHTOKEN,
      contentFields: [''],
      pages: '',
      pageTypes: '',
      typeName: 'Butter'
    };
  }
```
The naming of `GRIDSOME_` vs no prefix is defined in Gridsome docs and just determines if that key is shared within build code or not. So you want tp give the user an option.

2. Blog is currently automatic, but it may be that a user doesn't want to use the blog in their code, and f they are calling the plugin multiple times, there's no need to recreate the blog data within GraphQL (you actually create copies on different types (so in my case it created `ButterContentPosts` and `ButterDefaultPosts`, each with the same data which can get confusing for the developer when querying within their code. I'd make it opt-in instead of always on to keep the process down and your graphQL data trim.

Additionally, the code currently is:
```
for (const item of data) {
      contentType.addNode({
        title: item.title,
        url: item.url,
        featured_image: item.featured_image,
        slug: item.slug,
        created: item.created,
        published: item.published,
        summary: item.summary,
        seo_title: item.seo_title,
        body: item.body,
        meta_description: item.meta_description,
        status: item.status,
        author: item.author,
        tags: item.tags,
        categories: item.categories,
      });
    }
```

As this is a direct one-to-one mapping, you just need to do:

```
for (const item of data) {
      contentType.addNode(item);
}
```

or get somewhat fancy
```
for (const item of data) {
      contentType.addNode({
              ...item
      });
}
```

3. You are able to send multiple pages  and/or page types, but if they are different, then we receive an error. So you are unable to mix these. That can be left to explain in the documentation for now, but it may make sense to map `page_type` as its own typename, so:

```
pageTypes: [
          "general_content",
          "default_page_types"
        ],
```

can become GraphQL types like:

```
ButterGeneralContent
ButterDefaultPageTypes
```

4. ContentFields seem to work, but at least in workspaces you can't mix contentFields across Workspaces. This may not be able to be used with workspaces, and I think thats okay as we want users to be on Collections instead.

I would consider changing this from "ContentFields" to "Collections" instead for transparency reasons.


Thats all I got for now. It seems to work well as is, just needs documentation to describe how it works in its current form. I would consider implementing at least the `.env` lookup/mapping before release.

Great job, @lauragift21 !

**Comment by lauragift21** [comment]
Thanks @courcelan for the detailed feedback! I will work on these and revert back.

**Comment by lauragift21** [comment]
I just update the codebase with the feedback I was given. 

The 3rd point was a bit confusing. I generated a separate query for the `page-types`. 
In a situation where I have more than one page_types and map through it doesn't work as expected.

**Comment by jakelumetta** [comment]
@BobWalsh - can you take a look at the latest commits and let us know your thoughts?

**Comment by BobWalsh** [comment]
Hi @lauragift21 - do you have a working testbed project using this PR?

**Comment by lauragift21** [comment]
Yes, you can find it [here](https://github.com/lauragift21/gridsome-butter).
The content of this PR is located in `gridsome.server.js`

**Comment by jakelumetta** [comment]
Thanks Laura! Looks good.

**Pull request merged**
